import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from "../component/Navbar/Navbar";
import ProductList from "../component/Product/ProductList";
import {useRef, useState} from "react";
import {Context} from "../context/Context";

import { ScrollMenu, VisibilityContext } from 'react-horizontal-scrolling-menu';
export default function Home() {
    const scrollHandler = (e) => {
        e.preventDefault();
        const container = scrollRef.current;
        const containerScrollPosition = scrollRef.current.scrollLeft;

        container.scrollTo({
            top: 0,
            left: containerScrollPosition + e.deltaY,
        });

        console.log(e.deltaY)
    }
    const scrollRef = useRef(null);
    const [context, setContext] = useState(null);

    return (
        <Context.Provider value={[context, setContext]}>
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                {/*<link rel="icon" href="/favicon.ico" />*/}
            </Head>

            <Navbar/>
            <main className={`${styles.main}`} onWheel={scrollHandler} ref={scrollRef} >
                <ProductList/>
            </main>

        </> </Context.Provider>
    )
}
